### PR TITLE
:)

### PR DESCRIPTION
**Pull request by brillout**

### CODE REVIEW

**Comment by thomasjm** [comment]
Thanks @brillout ! 

This does help, although it's a bit weird because it depends on `../dist/server/importBuild.cjs` already existing. You basically have to run the build once without that import statement, and then run it again with the statement to get things to work. And of course you could get weird bugs if the file was stale.

I'm wondering if there's a way to fix this so it works with a single build from an empty directory? Maybe a pre-build step could generate `importBuild.cjs` first?

**Comment by brillout** [comment]
I'm not sure I understand what you mean (seems like you have a wrong perception of how things work). FYI avoiding the difficulties you encountered and making things simpler is very much on the radar.

**Comment by thomasjm** [comment]
Look, this is easy to verify -- just run the build of your branch in a clean directory and it will fail.

```bash
cd $(mktemp -d)
git clone git@github.com:brillout/vike-standalone.git
cd vike-standalone
pnpm install
pnpm run build
```

It's because you've tried to import a product of *the previous build*.

**Comment by brillout** [comment]
I see.

**Pull request merged**
